name: deploy

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and Check Package
        uses: hynek/build-and-inspect-python-package@v2.13.0

  deploy:
    needs: package
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # For PyPI trusted publishing.
      contents: write  # release notes.

    steps:
    - uses: actions/checkout@v3

    - name: Download Package
      uses: actions/download-artifact@v4.1.7
      with:
        name: Packages
        path: dist

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@v1.10.0
      with:
        attestations: true

    - name: GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
